name: Lint
on: [push, pull_request]
env:
  IMAGE: 'mlcaidev/ci-cpu:caab922'

jobs:
  isort:
    name: Python / isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ''
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/isort.sh

  black:
    name: Python / black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ''
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/black.sh

  mypy:
    name: Python / mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ''
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/mypy.sh

  pylint:
    name: Python / pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ''
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/pylint.sh

  clang-format:
    name: C++ / clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ''
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/clang-format.sh
