name: Python Lint

on: [push, pull_request]

env:
  IMAGE: 'mlcaidev/ci-cpu:8a87699'

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/isort.sh

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Version
      run: |
        wget https://raw.githubusercontent.com/mlc-ai/package/main/docker/bash.sh -O ./ci/bash.sh
        chmod u+x ./ci/bash.sh
        ./ci/bash.sh $IMAGE "conda env export --name ci-lint"
    - name: Lint
      run: |
        ./ci/bash.sh $IMAGE bash ./ci/task/black.sh
